#mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.2

#spring.data.mongodb.uri=mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.2
spring.data.mongodb.database=producto
spring.data.mongodb.uri=mongodb://mongo:D6BfACg3de1bbacFF-DCH1Dd6G3B61b6@viaduct.proxy.rlwy.net:49281